### ISSUE TITLE
Add Taiga

### ISSUE THREAD

**Issue by Xaviju** [dend/awesome-product-management#12]
Taiga is an open source project management tool for multi-functional agile teams. 
I think it makes sense in this list, but I am not PR it because I work on the Taiga team and I don't want to be marked as advertising.

Of course, I'd be happy to create the PR if you agree.

More info:

- https://www.taiga.io/
- https://github.com/kaleidos-ventures/taiga-front

**Comment by dend** [comment]
Thanks for checking in - I looked at the product and it makes sense to include in the list @Xaviju. Feel free to open a PR, and I can review and help merge.
